# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

TARGET   = KVS
TEMPLATE = lib
CONFIG  += static
CONFIG  += object_parallel_to_source
CONFIG += warn_off
include(KVS.conf)

DEFINES += NOMINMAX
DEFINES += WIN32_LEAN_AND_MEAN
DEFINES += KVS_SUPPORT_GLEW

INCLUDEPATH += $$PWD/Source
INCLUDEPATH += $$PWD/../../glew-2.1.0/include/
message($${INCLUDEPATH})


HEADERS = \
   Source/Core/FileFormat/AVSField/AVSField.h \
   Source/Core/FileFormat/AVSUCD/AVSUcd.h \
   Source/Core/FileFormat/BMP/Bmp.h \
   Source/Core/FileFormat/BMP/FileHeader.h \
   Source/Core/FileFormat/BMP/HeaderBase.h \
   Source/Core/FileFormat/BMP/InfoHeader.h \
   Source/Core/FileFormat/CSV/Csv.h \
   Source/Core/FileFormat/DICOM/Attribute.h \
   Source/Core/FileFormat/DICOM/DataType.h \
   Source/Core/FileFormat/DICOM/Dicom.h \
   Source/Core/FileFormat/DICOM/DicomList.h \
   Source/Core/FileFormat/DICOM/Element.h \
   Source/Core/FileFormat/DICOM/ElementType.h \
   Source/Core/FileFormat/DICOM/Item.h \
   Source/Core/FileFormat/DICOM/StreamReader.h \
   Source/Core/FileFormat/DICOM/Tag.h \
   Source/Core/FileFormat/DICOM/TagDictionary.h \
   Source/Core/FileFormat/DICOM/TagTable.h \
   Source/Core/FileFormat/DICOM/Value.h \
   Source/Core/FileFormat/DICOM/VR.h \
   Source/Core/FileFormat/DICOM/VRDictionary.h \
   Source/Core/FileFormat/DICOM/VRTable.h \
   Source/Core/FileFormat/DICOM/VRType.h \
   Source/Core/FileFormat/DICOM/Window.h \
   Source/Core/FileFormat/FrontFlow/BoundaryData.h \
   Source/Core/FileFormat/FrontFlow/Data.h \
   Source/Core/FileFormat/FrontFlow/DataSet.h \
   Source/Core/FileFormat/FrontFlow/File.h \
   Source/Core/FileFormat/FrontFlow/FlowData.h \
   Source/Core/FileFormat/FrontFlow/FrontFlow.h \
   Source/Core/FileFormat/FrontFlow/GFData.h \
   Source/Core/FileFormat/FrontFlow/MeshData.h \
   Source/Core/FileFormat/FrontSTR/FrontSTR.h \
   Source/Core/FileFormat/FrontSTR/MeshData.h \
   Source/Core/FileFormat/FrontSTR/ResultData.h \
   Source/Core/FileFormat/GrADS/DataDescriptorFile.h \
   Source/Core/FileFormat/GrADS/DSet.h \
   Source/Core/FileFormat/GrADS/GrADS.h \
   Source/Core/FileFormat/GrADS/GriddedBinaryDataFile.h \
   Source/Core/FileFormat/GrADS/Options.h \
   Source/Core/FileFormat/GrADS/TDef.h \
   Source/Core/FileFormat/GrADS/Title.h \
   Source/Core/FileFormat/GrADS/Undef.h \
   Source/Core/FileFormat/GrADS/Vars.h \
   Source/Core/FileFormat/GrADS/XDef.h \
   Source/Core/FileFormat/GrADS/XYZDef.h \
   Source/Core/FileFormat/GrADS/YDef.h \
   Source/Core/FileFormat/GrADS/ZDef.h \
   Source/Core/FileFormat/KVSML/CellTag.h \
   Source/Core/FileFormat/KVSML/ColorMapTag.h \
   Source/Core/FileFormat/KVSML/ColorTag.h \
   Source/Core/FileFormat/KVSML/ColumnTag.h \
   Source/Core/FileFormat/KVSML/ConnectionTag.h \
   Source/Core/FileFormat/KVSML/CoordTag.h \
   Source/Core/FileFormat/KVSML/DataArray.h \
   Source/Core/FileFormat/KVSML/DataArrayTag.h \
   Source/Core/FileFormat/KVSML/DataReader.h \
   Source/Core/FileFormat/KVSML/DataValueTag.h \
   Source/Core/FileFormat/KVSML/DataWriter.h \
   Source/Core/FileFormat/KVSML/ImageObjectTag.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectImage.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectLine.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectPoint.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectPolygon.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectStructuredVolume.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectTable.h \
   Source/Core/FileFormat/KVSML/KVSMLObjectUnstructuredVolume.h \
   Source/Core/FileFormat/KVSML/KVSMLTag.h \
   Source/Core/FileFormat/KVSML/KVSMLTransferFunction.h \
   Source/Core/FileFormat/KVSML/LineObjectTag.h \
   Source/Core/FileFormat/KVSML/LineTag.h \
   Source/Core/FileFormat/KVSML/NodeTag.h \
   Source/Core/FileFormat/KVSML/NormalTag.h \
   Source/Core/FileFormat/KVSML/ObjectTag.h \
   Source/Core/FileFormat/KVSML/OpacityMapTag.h \
   Source/Core/FileFormat/KVSML/OpacityTag.h \
   Source/Core/FileFormat/KVSML/PixelTag.h \
   Source/Core/FileFormat/KVSML/PointObjectTag.h \
   Source/Core/FileFormat/KVSML/PolygonObjectTag.h \
   Source/Core/FileFormat/KVSML/PolygonTag.h \
   Source/Core/FileFormat/KVSML/SizeTag.h \
   Source/Core/FileFormat/KVSML/StructuredVolumeObjectTag.h \
   Source/Core/FileFormat/KVSML/TableObjectTag.h \
   Source/Core/FileFormat/KVSML/TagBase.h \
   Source/Core/FileFormat/KVSML/TransferFunctionTag.h \
   Source/Core/FileFormat/KVSML/UnstructuredVolumeObjectTag.h \
   Source/Core/FileFormat/KVSML/ValueTag.h \
   Source/Core/FileFormat/KVSML/VertexTag.h \
   Source/Core/FileFormat/PLY/Ply.h \
   Source/Core/FileFormat/PLY/PlyFile.h \
   Source/Core/FileFormat/PNM/Header.h \
   Source/Core/FileFormat/PNM/Pbm.h \
   Source/Core/FileFormat/PNM/Pgm.h \
   Source/Core/FileFormat/PNM/Ppm.h \
   Source/Core/FileFormat/STL/Stl.h \
   Source/Core/FileFormat/TIFF/Entry.h \
   Source/Core/FileFormat/TIFF/Header.h \
   Source/Core/FileFormat/TIFF/ImageFileDirectory.h \
   Source/Core/FileFormat/TIFF/Tag.h \
   Source/Core/FileFormat/TIFF/TagDictionary.h \
   Source/Core/FileFormat/TIFF/TagTable.h \
   Source/Core/FileFormat/TIFF/Tiff.h \
   Source/Core/FileFormat/TIFF/ValueType.h \
   Source/Core/FileFormat/XML/TinyXML.h \
   Source/Core/FileFormat/XML/XMLComment.h \
   Source/Core/FileFormat/XML/XMLDeclaration.h \
   Source/Core/FileFormat/XML/XMLDocument.h \
   Source/Core/FileFormat/XML/XMLElement.h \
   Source/Core/FileFormat/XML/XMLNode.h \
   Source/Core/FileFormat/FileFormatBase.h \
   Source/Core/Image/BitImage.h \
   Source/Core/Image/ColorImage.h \
   Source/Core/Image/GrayImage.h \
   Source/Core/Image/HSVColor.h \
   Source/Core/Image/ImageBase.h \
   Source/Core/Image/RGBAColor.h \
   Source/Core/Image/RGBColor.h \
   Source/Core/Matrix/FrustumMatrix44.h \
   Source/Core/Matrix/LookAtMatrix44.h \
   Source/Core/Matrix/Matrix.h \
   Source/Core/Matrix/Matrix22.h \
   Source/Core/Matrix/Matrix33.h \
   Source/Core/Matrix/Matrix44.h \
   Source/Core/Matrix/OrthogonalMatrix44.h \
   Source/Core/Matrix/PerspectiveMatrix44.h \
   Source/Core/Matrix/RotationMatrix33.h \
   Source/Core/Matrix/ScalingMatrix33.h \
   Source/Core/Matrix/Vector.h \
   Source/Core/Matrix/Vector2.h \
   Source/Core/Matrix/Vector3.h \
   Source/Core/Matrix/Vector4.h \
   Source/Core/Matrix/ViewingMatrix44.h \
   Source/Core/Network/Acceptor.h \
   Source/Core/Network/Connector.h \
   Source/Core/Network/HttpConnector.h \
   Source/Core/Network/HttpRequestHeader.h \
   Source/Core/Network/IPAddress.h \
   Source/Core/Network/MessageBlock.h \
   Source/Core/Network/Socket.h \
   Source/Core/Network/SocketAddress.h \
   Source/Core/Network/SocketSelector.h \
   Source/Core/Network/SocketStandard.h \
   Source/Core/Network/SocketTimer.h \
   Source/Core/Network/TCPBarrier.h \
   Source/Core/Network/TCPBarrierServer.h \
   Source/Core/Network/TCPServer.h \
   Source/Core/Network/TCPSocket.h \
   Source/Core/Network/Url.h \
   Source/Core/Numeric/BoxMuller.h \
   Source/Core/Numeric/EigenDecomposer.h \
   Source/Core/Numeric/GaussEliminationSolver.h \
   Source/Core/Numeric/LUDecomposer.h \
   Source/Core/Numeric/LUSolver.h \
   Source/Core/Numeric/MersenneTwister.h \
   Source/Core/Numeric/QRDecomposer.h \
   Source/Core/Numeric/QRSolver.h \
   Source/Core/Numeric/Quaternion.h \
   Source/Core/Numeric/ResponseSurface.h \
   Source/Core/Numeric/SVDecomposer.h \
   Source/Core/Numeric/SVSolver.h \
   Source/Core/Numeric/Xorshift128.h \
   Source/Core/Thread/Condition.h \
   Source/Core/Thread/Mutex.h \
   Source/Core/Thread/MutexLocker.h \
   Source/Core/Thread/ReadLocker.h \
   Source/Core/Thread/ReadWriteLock.h \
   Source/Core/Thread/Semaphore.h \
   Source/Core/Thread/Thread.h \
   Source/Core/Thread/WriteLocker.h \
   Source/Core/Utility/AnyValue.h \
   Source/Core/Utility/AnyValueArray.h \
   Source/Core/Utility/Assert.h \
   Source/Core/Utility/Binary.h \
   Source/Core/Utility/BitArray.h \
   Source/Core/Utility/Breakpoint.h \
   Source/Core/Utility/ClassName.h \
   Source/Core/Utility/CommandLine.h \
   Source/Core/Utility/Compiler.h \
   Source/Core/Utility/Date.h \
   Source/Core/Utility/DebugNew.h \
   Source/Core/Utility/Directory.h \
   Source/Core/Utility/Endian.h \
   Source/Core/Utility/FastTokenizer.h \
   Source/Core/Utility/File.h \
   Source/Core/Utility/FileList.h \
   Source/Core/Utility/IgnoreUnusedVariable.h \
   Source/Core/Utility/Macro.h \
   Source/Core/Utility/Math.h \
   Source/Core/Utility/MemoryDebugger.h \
   Source/Core/Utility/MemoryTracer.h \
   Source/Core/Utility/Message.h \
   Source/Core/Utility/Platform.h \
   Source/Core/Utility/ReferenceCounter.h \
   Source/Core/Utility/String.h \
   Source/Core/Utility/StringList.h \
   Source/Core/Utility/SystemInformation.h \
   Source/Core/Utility/Time.h \
   Source/Core/Utility/Timer.h \
   Source/Core/Utility/Tokenizer.h \
   Source/Core/Utility/Tree.h \
   Source/Core/Utility/Type.h \
   Source/Core/Utility/Value.h \
   Source/Core/Utility/ValueArray.h \
   Source/Core/Utility/Version.h \
   Source/Core/Visualization/Data/HydrogenVolumeData.h \
   Source/Core/Visualization/Data/TornadoVolumeData.h \
   Source/Core/Visualization/Event/EventBase.h \
   Source/Core/Visualization/Event/EventHandler.h \
   Source/Core/Visualization/Event/EventListener.h \
   Source/Core/Visualization/Event/IdleEventListener.h \
   Source/Core/Visualization/Event/InitializeEventListener.h \
   Source/Core/Visualization/Event/KeyEvent.h \
   Source/Core/Visualization/Event/KeyPressEventListener.h \
   Source/Core/Visualization/Event/MouseDoubleClickEventListener.h \
   Source/Core/Visualization/Event/MouseEvent.h \
   Source/Core/Visualization/Event/MouseMoveEventListener.h \
   Source/Core/Visualization/Event/MousePressEventListener.h \
   Source/Core/Visualization/Event/MouseReleaseEventListener.h \
   Source/Core/Visualization/Event/PaintEventListener.h \
   Source/Core/Visualization/Event/ResizeEvent.h \
   Source/Core/Visualization/Event/ResizeEventListener.h \
   Source/Core/Visualization/Event/TimeEvent.h \
   Source/Core/Visualization/Event/TimerEventListener.h \
   Source/Core/Visualization/Event/WheelEvent.h \
   Source/Core/Visualization/Event/WheelEventListener.h \
   Source/Core/Visualization/Exporter/ExporterBase.h \
   Source/Core/Visualization/Exporter/LineExporter.h \
   Source/Core/Visualization/Exporter/PointExporter.h \
   Source/Core/Visualization/Exporter/PolygonExporter.h \
   Source/Core/Visualization/Exporter/StructuredVolumeExporter.h \
   Source/Core/Visualization/Exporter/UnstructuredVolumeExporter.h \
   Source/Core/Visualization/Filter/Bounds.h \
   Source/Core/Visualization/Filter/FilterBase.h \
   Source/Core/Visualization/Filter/LineIntegralConvolution.h \
   Source/Core/Visualization/Filter/StructuredVectorToScalar.h \
   Source/Core/Visualization/Filter/TetrahedraToTetrahedra.h \
   Source/Core/Visualization/Filter/TrilinearInterpolator.h \
   Source/Core/Visualization/Filter/Tubeline.h \
   Source/Core/Visualization/Filter/UnstructuredVectorToScalar.h \
   Source/Core/Visualization/Importer/ImageImporter.h \
   Source/Core/Visualization/Importer/ImporterBase.h \
   Source/Core/Visualization/Importer/LineImporter.h \
   Source/Core/Visualization/Importer/PointImporter.h \
   Source/Core/Visualization/Importer/PolygonImporter.h \
   Source/Core/Visualization/Importer/StructuredVolumeImporter.h \
   Source/Core/Visualization/Importer/TableImporter.h \
   Source/Core/Visualization/Importer/UnstructuredVolumeImporter.h \
   Source/Core/Visualization/Mapper/ArrowGlyph.h \
   Source/Core/Visualization/Mapper/CellAdjacencyGraph.h \
   Source/Core/Visualization/Mapper/CellBase.h \
   Source/Core/Visualization/Mapper/CellByCellLayeredSampling.h \
   Source/Core/Visualization/Mapper/CellByCellMetropolisSampling.h \
   Source/Core/Visualization/Mapper/CellByCellParticleGenerator.h \
   Source/Core/Visualization/Mapper/CellByCellRejectionSampling.h \
   Source/Core/Visualization/Mapper/CellByCellUniformSampling.h \
   Source/Core/Visualization/Mapper/ColorMap.h \
   Source/Core/Visualization/Mapper/DiamondGlyph.h \
   Source/Core/Visualization/Mapper/ExternalFaces.h \
   Source/Core/Visualization/Mapper/ExtractEdges.h \
   Source/Core/Visualization/Mapper/ExtractVertices.h \
   Source/Core/Visualization/Mapper/FrequencyTable.h \
   Source/Core/Visualization/Mapper/GlyphBase.h \
   Source/Core/Visualization/Mapper/HexahedralCell.h \
   Source/Core/Visualization/Mapper/HitAndMissSampling.h \
   Source/Core/Visualization/Mapper/Isosurface.h \
   Source/Core/Visualization/Mapper/MapperBase.h \
   Source/Core/Visualization/Mapper/MarchingCubes.h \
   Source/Core/Visualization/Mapper/MarchingCubesTable.h \
   Source/Core/Visualization/Mapper/MarchingHexahedra.h \
   Source/Core/Visualization/Mapper/MarchingHexahedraTable.h \
   Source/Core/Visualization/Mapper/MarchingPyramid.h \
   Source/Core/Visualization/Mapper/MarchingPyramidTable.h \
   Source/Core/Visualization/Mapper/MarchingTetrahedra.h \
   Source/Core/Visualization/Mapper/MarchingTetrahedraTable.h \
   Source/Core/Visualization/Mapper/MetropolisSampling.h \
   Source/Core/Visualization/Mapper/OpacityMap.h \
   Source/Core/Visualization/Mapper/OrthoSlice.h \
   Source/Core/Visualization/Mapper/PyramidalCell.h \
   Source/Core/Visualization/Mapper/QuadraticHexahedralCell.h \
   Source/Core/Visualization/Mapper/QuadraticTetrahedralCell.h \
   Source/Core/Visualization/Mapper/RGBFormulae.h \
   Source/Core/Visualization/Mapper/SlicePlane.h \
   Source/Core/Visualization/Mapper/SphereGlyph.h \
   Source/Core/Visualization/Mapper/Streamline.h \
   Source/Core/Visualization/Mapper/StreamlineBase.h \
   Source/Core/Visualization/Mapper/TetrahedralCell.h \
   Source/Core/Visualization/Mapper/TransferFunction.h \
   Source/Core/Visualization/Object/AxisObject.h \
   Source/Core/Visualization/Object/GeometryObjectBase.h \
   Source/Core/Visualization/Object/GlyphObject.h \
   Source/Core/Visualization/Object/ImageObject.h \
   Source/Core/Visualization/Object/LineObject.h \
   Source/Core/Visualization/Object/ObjectBase.h \
   Source/Core/Visualization/Object/PointObject.h \
   Source/Core/Visualization/Object/PolygonObject.h \
   Source/Core/Visualization/Object/StructuredVolumeObject.h \
   Source/Core/Visualization/Object/TableObject.h \
   Source/Core/Visualization/Object/UnstructuredVolumeObject.h \
   Source/Core/Visualization/Object/VolumeObjectBase.h \
   Source/Core/Visualization/Pipeline/ObjectImporter.h \
   Source/Core/Visualization/Pipeline/PipelineModule.h \
   Source/Core/Visualization/Pipeline/VisualizationPipeline.h \
   Source/Core/Visualization/Renderer/GlyphRenderer.h \
   Source/Core/Visualization/Renderer/ImageRenderer.h \
   Source/Core/Visualization/Renderer/LineRenderer.h \
   Source/Core/Visualization/Renderer/LineRenderingFunction.h \
   Source/Core/Visualization/Renderer/ParallelCoordinatesRenderer.h \
   Source/Core/Visualization/Renderer/ParticleBuffer.h \
   Source/Core/Visualization/Renderer/ParticleBufferAccumulator.h \
   Source/Core/Visualization/Renderer/ParticleBufferCompositor.h \
   Source/Core/Visualization/Renderer/ParticleVolumeRenderer.h \
   Source/Core/Visualization/Renderer/PointRenderer.h \
   Source/Core/Visualization/Renderer/PointRenderingFunction.h \
   Source/Core/Visualization/Renderer/PolygonRenderer.h \
   Source/Core/Visualization/Renderer/PolygonRenderingFunction.h \
   Source/Core/Visualization/Renderer/Ray.h \
   Source/Core/Visualization/Renderer/RayCastingRenderer.h \
   Source/Core/Visualization/Renderer/RendererBase.h \
   Source/Core/Visualization/Renderer/ScatterPlotMatrixRenderer.h \
   Source/Core/Visualization/Renderer/ScatterPlotRenderer.h \
   Source/Core/Visualization/Renderer/Shader.h \
   Source/Core/Visualization/Renderer/VolumeRayIntersector.h \
   Source/Core/Visualization/Renderer/VolumeRendererBase.h \
   Source/Core/Visualization/Viewer/ApplicationBase.h \
   Source/Core/Visualization/Viewer/Background.h \
   Source/Core/Visualization/Viewer/Camera.h \
   Source/Core/Visualization/Viewer/DisplayFormat.h \
   Source/Core/Visualization/Viewer/DisplayList.h \
   Source/Core/Visualization/Viewer/FrameBuffer.h \
   Source/Core/Visualization/Viewer/GlobalCore.h \
   Source/Core/Visualization/Viewer/IDManager.h \
   Source/Core/Visualization/Viewer/Key.h \
   Source/Core/Visualization/Viewer/Light.h \
   Source/Core/Visualization/Viewer/Material.h \
   Source/Core/Visualization/Viewer/Mouse.h \
   Source/Core/Visualization/Viewer/MouseButton.h \
   Source/Core/Visualization/Viewer/ObjectManager.h \
   Source/Core/Visualization/Viewer/OpenGL.h \
   Source/Core/Visualization/Viewer/RendererManager.h \
   Source/Core/Visualization/Viewer/ScreenBase.h \
   Source/Core/Visualization/Viewer/ScreenCore.h \
   Source/Core/Visualization/Viewer/Texture1D.h \
   Source/Core/Visualization/Viewer/Texture2D.h \
   Source/Core/Visualization/Viewer/TextureBase.h \
   Source/Core/Visualization/Viewer/Trackball.h \
   Source/Core/Visualization/Viewer/WindowBase.h \
   Source/Core/Visualization/Viewer/Xform.h \
   Source/Core/Visualization/Viewer/XformControl.h \
   Source/Core/Visualization/Module.h \
   Source/kvs/glew/BufferObject \
   Source/kvs/glew/EnsembleAverageBuffer \
   Source/kvs/glew/FragmentShader \
   Source/kvs/glew/FrameBufferObject \
   Source/kvs/glew/GeometryShader \
   Source/kvs/glew/GLEW \
   Source/kvs/glew/IndexBufferObject \
   Source/kvs/glew/ParticleVolumeRenderer \
   Source/kvs/glew/PixelBufferObject \
   Source/kvs/glew/PointRenderer \
   Source/kvs/glew/PolygonRenderer \
   Source/kvs/glew/ProgramObject \
   Source/kvs/glew/RayCastingRenderer \
   Source/kvs/glew/RenderBuffer \
   Source/kvs/glew/Shader \
   Source/kvs/glew/ShaderObject \
   Source/kvs/glew/ShaderSource \
   Source/kvs/glew/Texture3D \
   Source/kvs/glew/TextureRectangle \
   Source/kvs/glew/VertexBufferObject \
   Source/kvs/glew/VertexShader \
#   Source/kvs/opencabin/Application \
#   Source/kvs/opencabin/Camera \
#   Source/kvs/opencabin/Configuration \
#   Source/kvs/opencabin/MainLoop \
#   Source/kvs/opencabin/Master \
#   Source/kvs/opencabin/OpenCABIN \
#   Source/kvs/opencabin/Screen \
#   Source/kvs/opencabin/Trackpad \
#   Source/kvs/opencv/CaptureDevice \
#   Source/kvs/opencv/OpenCV \
#   Source/kvs/opencv/VideoObject \
#   Source/kvs/opencv/VideoRenderer \
#   Source/kvs/opencv/Window \
#   Source/kvs/qt/Application \
#   Source/kvs/qt/GlobalBase \
#   Source/kvs/qt/Qt \
#   Source/kvs/qt/Screen \
#   Source/kvs/qt/ScreenBase \
#   Source/kvs/qt/Timer \
#   Source/kvs/qt/Window \
#   Source/kvs/sage/Application \
#   Source/kvs/sage/ApplicationInterface \
#   Source/kvs/sage/GlobalBase \
#   Source/kvs/sage/SAGE \
#   Source/kvs/sage/Screen \
#   Source/kvs/sage/ScreenBase \
   Source/kvs/Acceptor \
   Source/kvs/AnyValue \
   Source/kvs/AnyValueArray \
   Source/kvs/ApplicationBase \
   Source/kvs/ArrowGlyph \
   Source/kvs/Assert \
   Source/kvs/AVSField \
   Source/kvs/AVSUcd \
   Source/kvs/AxisObject \
   Source/kvs/Background \
   Source/kvs/Binary \
   Source/kvs/BitArray \
   Source/kvs/BitImage \
   Source/kvs/Bmp \
   Source/kvs/Bounds \
   Source/kvs/BoxMuller \
   Source/kvs/Breakpoint \
   Source/kvs/Camera \
   Source/kvs/CellAdjacencyGraph \
   Source/kvs/CellBase \
   Source/kvs/CellByCellLayeredSampling \
   Source/kvs/CellByCellMetropolisSampling \
   Source/kvs/CellByCellParticleGenerator \
   Source/kvs/CellByCellRejectionSampling \
   Source/kvs/CellByCellUniformSampling \
   Source/kvs/ClassName \
   Source/kvs/ColorImage \
   Source/kvs/ColorMap \
   Source/kvs/CommandLine \
   Source/kvs/Compiler \
   Source/kvs/Condition \
   Source/kvs/Connector \
   Source/kvs/Csv \
   Source/kvs/Date \
   Source/kvs/DebugNew \
   Source/kvs/DiamondGlyph \
   Source/kvs/Dicom \
   Source/kvs/DicomList \
   Source/kvs/Directory \
   Source/kvs/DisplayFormat \
   Source/kvs/DisplayList \
   Source/kvs/EigenDecomposer \
   Source/kvs/Endian \
   Source/kvs/EventBase \
   Source/kvs/EventHandler \
   Source/kvs/EventListener \
   Source/kvs/ExporterBase \
   Source/kvs/ExternalFaces \
   Source/kvs/ExtractEdges \
   Source/kvs/ExtractVertices \
   Source/kvs/FastTokenizer \
   Source/kvs/File \
   Source/kvs/FileFormatBase \
   Source/kvs/FileList \
   Source/kvs/FilterBase \
   Source/kvs/FrameBuffer \
   Source/kvs/FrequencyTable \
   Source/kvs/FrontFlow \
   Source/kvs/FrontSTR \
   Source/kvs/FrustumMatrix44 \
   Source/kvs/GaussEliminationSolver \
   Source/kvs/GeometryObjectBase \
   Source/kvs/GlobalCore \
   Source/kvs/GlyphBase \
   Source/kvs/GlyphObject \
   Source/kvs/GlyphRenderer \
   Source/kvs/GrADS \
   Source/kvs/GrayImage \
   Source/kvs/HexahedralCell \
   Source/kvs/HitAndMissSampling \
   Source/kvs/HSVColor \
   Source/kvs/HttpConnector \
   Source/kvs/HttpRequestHeader \
   Source/kvs/HydrogenVolumeData \
   Source/kvs/IdleEventListener \
   Source/kvs/IDManager \
   Source/kvs/IgnoreUnusedVariable \
   Source/kvs/ImageBase \
   Source/kvs/ImageImporter \
   Source/kvs/ImageObject \
   Source/kvs/ImageRenderer \
   Source/kvs/ImporterBase \
   Source/kvs/InitializeEventListener \
   Source/kvs/IPAddress \
   Source/kvs/Isosurface \
   Source/kvs/Key \
   Source/kvs/KeyEvent \
   Source/kvs/KeyPressEventListener \
   Source/kvs/KVSMLObjectImage \
   Source/kvs/KVSMLObjectLine \
   Source/kvs/KVSMLObjectPoint \
   Source/kvs/KVSMLObjectPolygon \
   Source/kvs/KVSMLObjectStructuredVolume \
   Source/kvs/KVSMLObjectTable \
   Source/kvs/KVSMLObjectUnstructuredVolume \
   Source/kvs/KVSMLTransferFunction \
   Source/kvs/Light \
   Source/kvs/LineExporter \
   Source/kvs/LineImporter \
   Source/kvs/LineIntegralConvolution \
   Source/kvs/LineObject \
   Source/kvs/LineRenderer \
   Source/kvs/LookAtMatrix44 \
   Source/kvs/LUDecomposer \
   Source/kvs/LUSolver \
   Source/kvs/Macro \
   Source/kvs/MapperBase \
   Source/kvs/MarchingCubes \
   Source/kvs/MarchingCubesTable \
   Source/kvs/MarchingHexahedra \
   Source/kvs/MarchingHexahedraTable \
   Source/kvs/MarchingPyramid \
   Source/kvs/MarchingPyramidTable \
   Source/kvs/MarchingTetrahedra \
   Source/kvs/MarchingTetrahedraTable \
   Source/kvs/Material \
   Source/kvs/Math \
   Source/kvs/Matrix \
   Source/kvs/Matrix22 \
   Source/kvs/Matrix33 \
   Source/kvs/Matrix44 \
   Source/kvs/MemoryDebugger \
   Source/kvs/MemoryTracer \
   Source/kvs/MersenneTwister \
   Source/kvs/Message \
   Source/kvs/MessageBlock \
   Source/kvs/MetropolisSampling \
   Source/kvs/Module \
   Source/kvs/Mouse \
   Source/kvs/MouseButton \
   Source/kvs/MouseDoubleClickEventListener \
   Source/kvs/MouseEvent \
   Source/kvs/MouseMoveEventListener \
   Source/kvs/MousePressEventListener \
   Source/kvs/MouseReleaseEventListener \
   Source/kvs/Mutex \
   Source/kvs/MutexLocker \
   Source/kvs/ObjectBase \
   Source/kvs/ObjectImporter \
   Source/kvs/ObjectManager \
   Source/kvs/OpacityMap \
   Source/kvs/OpenGL \
   Source/kvs/OrthogonalMatrix44 \
   Source/kvs/OrthoSlice \
   Source/kvs/PaintEventListener \
   Source/kvs/ParallelCoordinatesRenderer \
   Source/kvs/ParticleBuffer \
   Source/kvs/ParticleBufferAccumulator \
   Source/kvs/ParticleBufferCompositor \
   Source/kvs/ParticleVolumeRenderer \
   Source/kvs/Pbm \
   Source/kvs/PerspectiveMatrix44 \
   Source/kvs/Pgm \
   Source/kvs/PipelineModule \
   Source/kvs/Platform \
   Source/kvs/Ply \
   Source/kvs/PointExporter \
   Source/kvs/PointImporter \
   Source/kvs/PointObject \
   Source/kvs/PointRenderer \
   Source/kvs/PolygonExporter \
   Source/kvs/PolygonImporter \
   Source/kvs/PolygonObject \
   Source/kvs/PolygonRenderer \
   Source/kvs/Ppm \
   Source/kvs/PyramidalCell \
   Source/kvs/QRDecomposer \
   Source/kvs/QRSolver \
   Source/kvs/QuadraticHexahedralCell \
   Source/kvs/QuadraticTetrahedralCell \
   Source/kvs/Quaternion \
   Source/kvs/Ray \
   Source/kvs/RayCastingRenderer \
   Source/kvs/ReadLocker \
   Source/kvs/ReadWriteLock \
   Source/kvs/ReferenceCounter \
   Source/kvs/RendererBase \
   Source/kvs/RendererManager \
   Source/kvs/ResizeEvent \
   Source/kvs/ResizeEventListener \
   Source/kvs/ResponseSurface \
   Source/kvs/RGBAColor \
   Source/kvs/RGBColor \
   Source/kvs/RGBFormulae \
   Source/kvs/RotationMatrix33 \
   Source/kvs/ScalingMatrix33 \
   Source/kvs/ScatterPlotMatrixRenderer \
   Source/kvs/ScatterPlotRenderer \
   Source/kvs/ScreenBase \
   Source/kvs/ScreenCore \
   Source/kvs/Semaphore \
   Source/kvs/Shader \
   Source/kvs/SlicePlane \
   Source/kvs/Socket \
   Source/kvs/SocketAddress \
   Source/kvs/SocketSelector \
   Source/kvs/SocketTimer \
   Source/kvs/SphereGlyph \
   Source/kvs/Stl \
   Source/kvs/Streamline \
   Source/kvs/StreamlineBase \
   Source/kvs/String \
   Source/kvs/StringList \
   Source/kvs/StructuredVectorToScalar \
   Source/kvs/StructuredVolumeExporter \
   Source/kvs/StructuredVolumeImporter \
   Source/kvs/StructuredVolumeObject \
   Source/kvs/SVDecomposer \
   Source/kvs/SVSolver \
   Source/kvs/SystemInformation \
   Source/kvs/TableImporter \
   Source/kvs/TableObject \
   Source/kvs/TCPBarrier \
   Source/kvs/TCPBarrierServer \
   Source/kvs/TCPServer \
   Source/kvs/TCPSocket \
   Source/kvs/TetrahedralCell \
   Source/kvs/TetrahedraToTetrahedra \
   Source/kvs/Texture1D \
   Source/kvs/Texture2D \
   Source/kvs/TextureBase \
   Source/kvs/Thread \
   Source/kvs/Tiff \
   Source/kvs/Time \
   Source/kvs/TimeEvent \
   Source/kvs/Timer \
   Source/kvs/TimerEventListener \
   Source/kvs/Tokenizer \
   Source/kvs/TornadoVolumeData \
   Source/kvs/Trackball \
   Source/kvs/TransferFunction \
   Source/kvs/Tree \
   Source/kvs/TrilinearInterpolator \
   Source/kvs/Tubeline \
   Source/kvs/Type \
   Source/kvs/UnstructuredVectorToScalar \
   Source/kvs/UnstructuredVolumeExporter \
   Source/kvs/UnstructuredVolumeImporter \
   Source/kvs/UnstructuredVolumeObject \
   Source/kvs/Url \
   Source/kvs/Value \
   Source/kvs/ValueArray \
   Source/kvs/Vector \
   Source/kvs/Vector2 \
   Source/kvs/Vector3 \
   Source/kvs/Vector4 \
   Source/kvs/Version \
   Source/kvs/ViewingMatrix44 \
   Source/kvs/VisualizationPipeline \
   Source/kvs/VolumeObjectBase \
   Source/kvs/VolumeRayIntersector \
   Source/kvs/VolumeRendererBase \
   Source/kvs/WheelEvent \
   Source/kvs/WheelEventListener \
   Source/kvs/WindowBase \
   Source/kvs/WriteLocker \
   Source/kvs/Xform \
   Source/kvs/XformControl \
   Source/kvs/XMLComment \
   Source/kvs/XMLDeclaration \
   Source/kvs/XMLDocument \
   Source/kvs/XMLElement \
   Source/kvs/XMLNode \
   Source/kvs/Xorshift128 \
   Source/kvsCore \
   Source/SupportGLEW/Renderer/ParticleVolumeRenderer/Shader.h \
   Source/SupportGLEW/Renderer/PointRenderer/Shader.h \
   Source/SupportGLEW/Renderer/PolygonRenderer/Shader.h \
   Source/SupportGLEW/Renderer/RayCastingRenderer/Shader.h \
   Source/SupportGLEW/Renderer/Shader/shading.h \
   Source/SupportGLEW/Renderer/Shader/transfer_function.h \
   Source/SupportGLEW/Renderer/Shader/volume.h \
   Source/SupportGLEW/Renderer/EnsembleAverageBuffer.h \
   Source/SupportGLEW/Renderer/ParticleVolumeRenderer.h \
   Source/SupportGLEW/Renderer/PointRenderer.h \
   Source/SupportGLEW/Renderer/PolygonRenderer.h \
   Source/SupportGLEW/Renderer/RayCastingRenderer.h \
   Source/SupportGLEW/Viewer/BufferObject.h \
   Source/SupportGLEW/Viewer/FragmentShader.h \
   Source/SupportGLEW/Viewer/FrameBufferObject.h \
   Source/SupportGLEW/Viewer/GeometryShader.h \
   Source/SupportGLEW/Viewer/IndexBufferObject.h \
   Source/SupportGLEW/Viewer/PixelBufferObject.h \
   Source/SupportGLEW/Viewer/ProgramObject.h \
   Source/SupportGLEW/Viewer/RenderBuffer.h \
   Source/SupportGLEW/Viewer/ShaderObject.h \
   Source/SupportGLEW/Viewer/ShaderSource.h \
   Source/SupportGLEW/Viewer/Texture3D.h \
   Source/SupportGLEW/Viewer/TextureRectangle.h \
   Source/SupportGLEW/Viewer/VertexBufferObject.h \
   Source/SupportGLEW/Viewer/VertexShader.h \
   Source/SupportGLEW/GLEW.h \
   Source/kvsSupportGLEW

SOURCES = \
   Source/Core/FileFormat/AVSField/AVSField.cpp \
   Source/Core/FileFormat/AVSUCD/AVSUcd.cpp \
   Source/Core/FileFormat/BMP/Bmp.cpp \
   Source/Core/FileFormat/BMP/FileHeader.cpp \
   Source/Core/FileFormat/BMP/InfoHeader.cpp \
   Source/Core/FileFormat/CSV/Csv.cpp \
   Source/Core/FileFormat/DICOM/Attribute.cpp \
   Source/Core/FileFormat/DICOM/Dicom.cpp \
   Source/Core/FileFormat/DICOM/DicomList.cpp \
   Source/Core/FileFormat/DICOM/Element.cpp \
   Source/Core/FileFormat/DICOM/Item.cpp \
   Source/Core/FileFormat/DICOM/Tag.cpp \
   Source/Core/FileFormat/DICOM/Value.cpp \
   Source/Core/FileFormat/DICOM/VR.cpp \
   Source/Core/FileFormat/DICOM/Window.cpp \
   Source/Core/FileFormat/FrontFlow/BoundaryData.cpp \
   Source/Core/FileFormat/FrontFlow/Data.cpp \
   Source/Core/FileFormat/FrontFlow/DataSet.cpp \
   Source/Core/FileFormat/FrontFlow/File.cpp \
   Source/Core/FileFormat/FrontFlow/FlowData.cpp \
   Source/Core/FileFormat/FrontFlow/GFData.cpp \
   Source/Core/FileFormat/FrontFlow/MeshData.cpp \
   Source/Core/FileFormat/FrontSTR/FrontSTR.cpp \
   Source/Core/FileFormat/FrontSTR/MeshData.cpp \
   Source/Core/FileFormat/FrontSTR/ResultData.cpp \
   Source/Core/FileFormat/GrADS/DataDescriptorFile.cpp \
   Source/Core/FileFormat/GrADS/DSet.cpp \
   Source/Core/FileFormat/GrADS/GrADS.cpp \
   Source/Core/FileFormat/GrADS/GriddedBinaryDataFile.cpp \
   Source/Core/FileFormat/GrADS/Options.cpp \
   Source/Core/FileFormat/GrADS/TDef.cpp \
   Source/Core/FileFormat/GrADS/Title.cpp \
   Source/Core/FileFormat/GrADS/Undef.cpp \
   Source/Core/FileFormat/GrADS/Vars.cpp \
   Source/Core/FileFormat/GrADS/XYZDef.cpp \
   Source/Core/FileFormat/KVSML/CellTag.cpp \
   Source/Core/FileFormat/KVSML/ColorMapTag.cpp \
   Source/Core/FileFormat/KVSML/ColorTag.cpp \
   Source/Core/FileFormat/KVSML/ColumnTag.cpp \
   Source/Core/FileFormat/KVSML/ConnectionTag.cpp \
   Source/Core/FileFormat/KVSML/CoordTag.cpp \
   Source/Core/FileFormat/KVSML/DataArrayTag.cpp \
   Source/Core/FileFormat/KVSML/DataReader.cpp \
   Source/Core/FileFormat/KVSML/DataValueTag.cpp \
   Source/Core/FileFormat/KVSML/DataWriter.cpp \
   Source/Core/FileFormat/KVSML/ImageObjectTag.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectImage.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectLine.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectPoint.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectPolygon.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectStructuredVolume.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectTable.cpp \
   Source/Core/FileFormat/KVSML/KVSMLObjectUnstructuredVolume.cpp \
   Source/Core/FileFormat/KVSML/KVSMLTag.cpp \
   Source/Core/FileFormat/KVSML/KVSMLTransferFunction.cpp \
   Source/Core/FileFormat/KVSML/LineObjectTag.cpp \
   Source/Core/FileFormat/KVSML/LineTag.cpp \
   Source/Core/FileFormat/KVSML/NodeTag.cpp \
   Source/Core/FileFormat/KVSML/NormalTag.cpp \
   Source/Core/FileFormat/KVSML/ObjectTag.cpp \
   Source/Core/FileFormat/KVSML/OpacityMapTag.cpp \
   Source/Core/FileFormat/KVSML/OpacityTag.cpp \
   Source/Core/FileFormat/KVSML/PixelTag.cpp \
   Source/Core/FileFormat/KVSML/PointObjectTag.cpp \
   Source/Core/FileFormat/KVSML/PolygonObjectTag.cpp \
   Source/Core/FileFormat/KVSML/PolygonTag.cpp \
   Source/Core/FileFormat/KVSML/SizeTag.cpp \
   Source/Core/FileFormat/KVSML/StructuredVolumeObjectTag.cpp \
   Source/Core/FileFormat/KVSML/TableObjectTag.cpp \
   Source/Core/FileFormat/KVSML/TagBase.cpp \
   Source/Core/FileFormat/KVSML/TransferFunctionTag.cpp \
   Source/Core/FileFormat/KVSML/UnstructuredVolumeObjectTag.cpp \
   Source/Core/FileFormat/KVSML/ValueTag.cpp \
   Source/Core/FileFormat/KVSML/VertexTag.cpp \
   Source/Core/FileFormat/PLY/Ply.cpp \
   Source/Core/FileFormat/PLY/PlyFile.cpp \
   Source/Core/FileFormat/PNM/Header.cpp \
   Source/Core/FileFormat/PNM/Pbm.cpp \
   Source/Core/FileFormat/PNM/Pgm.cpp \
   Source/Core/FileFormat/PNM/Ppm.cpp \
   Source/Core/FileFormat/STL/Stl.cpp \
   Source/Core/FileFormat/TIFF/Entry.cpp \
   Source/Core/FileFormat/TIFF/Header.cpp \
   Source/Core/FileFormat/TIFF/ImageFileDirectory.cpp \
   Source/Core/FileFormat/TIFF/Tag.cpp \
   Source/Core/FileFormat/TIFF/TagDictionary.cpp \
   Source/Core/FileFormat/TIFF/Tiff.cpp \
   Source/Core/FileFormat/XML/TinyXML.cpp \
   Source/Core/FileFormat/XML/XMLComment.cpp \
   Source/Core/FileFormat/XML/XMLDeclaration.cpp \
   Source/Core/FileFormat/XML/XMLDocument.cpp \
   Source/Core/FileFormat/XML/XMLElement.cpp \
   Source/Core/FileFormat/XML/XMLNode.cpp \
   Source/Core/FileFormat/FileFormatBase.cpp \
   Source/Core/Image/BitImage.cpp \
   Source/Core/Image/ColorImage.cpp \
   Source/Core/Image/GrayImage.cpp \
   Source/Core/Image/HSVColor.cpp \
   Source/Core/Image/ImageBase.cpp \
   Source/Core/Image/RGBAColor.cpp \
   Source/Core/Image/RGBColor.cpp \
   Source/Core/Matrix/FrustumMatrix44.cpp \
   Source/Core/Matrix/LookAtMatrix44.cpp \
   Source/Core/Matrix/Matrix.cpp \
   Source/Core/Matrix/Matrix22.cpp \
   Source/Core/Matrix/Matrix33.cpp \
   Source/Core/Matrix/Matrix44.cpp \
   Source/Core/Matrix/OrthogonalMatrix44.cpp \
   Source/Core/Matrix/PerspectiveMatrix44.cpp \
   Source/Core/Matrix/RotationMatrix33.cpp \
   Source/Core/Matrix/ScalingMatrix33.cpp \
   Source/Core/Matrix/Vector.cpp \
   Source/Core/Matrix/Vector2.cpp \
   Source/Core/Matrix/Vector3.cpp \
   Source/Core/Matrix/Vector4.cpp \
   Source/Core/Matrix/ViewingMatrix44.cpp \
   Source/Core/Network/Acceptor.cpp \
   Source/Core/Network/Connector.cpp \
   Source/Core/Network/HttpConnector.cpp \
   Source/Core/Network/HttpRequestHeader.cpp \
   Source/Core/Network/IPAddress.cpp \
   Source/Core/Network/MessageBlock.cpp \
   Source/Core/Network/Socket.cpp \
   Source/Core/Network/SocketAddress.cpp \
   Source/Core/Network/SocketSelector.cpp \
   Source/Core/Network/SocketTimer.cpp \
   Source/Core/Network/TCPBarrier.cpp \
   Source/Core/Network/TCPBarrierServer.cpp \
   Source/Core/Network/TCPServer.cpp \
   Source/Core/Network/TCPSocket.cpp \
   Source/Core/Network/Url.cpp \
   Source/Core/Numeric/EigenDecomposer.cpp \
   Source/Core/Numeric/GaussEliminationSolver.cpp \
   Source/Core/Numeric/LUDecomposer.cpp \
   Source/Core/Numeric/LUSolver.cpp \
   Source/Core/Numeric/MersenneTwister.cpp \
   Source/Core/Numeric/QRDecomposer.cpp \
   Source/Core/Numeric/QRSolver.cpp \
   Source/Core/Numeric/Quaternion.cpp \
   Source/Core/Numeric/ResponseSurface.cpp \
   Source/Core/Numeric/SVDecomposer.cpp \
   Source/Core/Numeric/SVSolver.cpp \
   Source/Core/Numeric/Xorshift128.cpp \
   Source/Core/Thread/Condition.cpp \
   Source/Core/Thread/Mutex.cpp \
   Source/Core/Thread/MutexLocker.cpp \
   Source/Core/Thread/ReadLocker.cpp \
   Source/Core/Thread/ReadWriteLock.cpp \
   Source/Core/Thread/Semaphore.cpp \
   Source/Core/Thread/Thread.cpp \
   Source/Core/Thread/WriteLocker.cpp \
   Source/Core/Utility/AnyValue.cpp \
   Source/Core/Utility/AnyValueArray.cpp \
   Source/Core/Utility/BitArray.cpp \
   Source/Core/Utility/CommandLine.cpp \
   Source/Core/Utility/Date.cpp \
   Source/Core/Utility/Directory.cpp \
   Source/Core/Utility/FastTokenizer.cpp \
   Source/Core/Utility/File.cpp \
   Source/Core/Utility/MemoryTracer.cpp \
   Source/Core/Utility/Message.cpp \
   Source/Core/Utility/ReferenceCounter.cpp \
   Source/Core/Utility/String.cpp \
   Source/Core/Utility/SystemInformation.cpp \
   Source/Core/Utility/Time.cpp \
   Source/Core/Utility/Tokenizer.cpp \
   Source/Core/Utility/Value.cpp \
   Source/Core/Utility/ValueArray.cpp \
   Source/Core/Visualization/Data/HydrogenVolumeData.cpp \
   Source/Core/Visualization/Data/TornadoVolumeData.cpp \
   Source/Core/Visualization/Event/EventBase.cpp \
   Source/Core/Visualization/Event/EventHandler.cpp \
   Source/Core/Visualization/Event/EventListener.cpp \
   Source/Core/Visualization/Event/IdleEventListener.cpp \
   Source/Core/Visualization/Event/InitializeEventListener.cpp \
   Source/Core/Visualization/Event/KeyEvent.cpp \
   Source/Core/Visualization/Event/KeyPressEventListener.cpp \
   Source/Core/Visualization/Event/MouseDoubleClickEventListener.cpp \
   Source/Core/Visualization/Event/MouseEvent.cpp \
   Source/Core/Visualization/Event/MouseMoveEventListener.cpp \
   Source/Core/Visualization/Event/MousePressEventListener.cpp \
   Source/Core/Visualization/Event/MouseReleaseEventListener.cpp \
   Source/Core/Visualization/Event/PaintEventListener.cpp \
   Source/Core/Visualization/Event/ResizeEvent.cpp \
   Source/Core/Visualization/Event/ResizeEventListener.cpp \
   Source/Core/Visualization/Event/TimeEvent.cpp \
   Source/Core/Visualization/Event/TimerEventListener.cpp \
   Source/Core/Visualization/Event/WheelEvent.cpp \
   Source/Core/Visualization/Event/WheelEventListener.cpp \
   Source/Core/Visualization/Exporter/LineExporter.cpp \
   Source/Core/Visualization/Exporter/PointExporter.cpp \
   Source/Core/Visualization/Exporter/PolygonExporter.cpp \
   Source/Core/Visualization/Exporter/StructuredVolumeExporter.cpp \
   Source/Core/Visualization/Exporter/UnstructuredVolumeExporter.cpp \
   Source/Core/Visualization/Filter/Bounds.cpp \
   Source/Core/Visualization/Filter/FilterBase.cpp \
   Source/Core/Visualization/Filter/LineIntegralConvolution.cpp \
   Source/Core/Visualization/Filter/StructuredVectorToScalar.cpp \
   Source/Core/Visualization/Filter/TetrahedraToTetrahedra.cpp \
   Source/Core/Visualization/Filter/TrilinearInterpolator.cpp \
   Source/Core/Visualization/Filter/Tubeline.cpp \
   Source/Core/Visualization/Filter/UnstructuredVectorToScalar.cpp \
   Source/Core/Visualization/Importer/ImageImporter.cpp \
   Source/Core/Visualization/Importer/ImporterBase.cpp \
   Source/Core/Visualization/Importer/LineImporter.cpp \
   Source/Core/Visualization/Importer/PointImporter.cpp \
   Source/Core/Visualization/Importer/PolygonImporter.cpp \
   Source/Core/Visualization/Importer/StructuredVolumeImporter.cpp \
   Source/Core/Visualization/Importer/TableImporter.cpp \
   Source/Core/Visualization/Importer/UnstructuredVolumeImporter.cpp \
   Source/Core/Visualization/Mapper/ArrowGlyph.cpp \
   Source/Core/Visualization/Mapper/CellAdjacencyGraph.cpp \
   Source/Core/Visualization/Mapper/CellByCellLayeredSampling.cpp \
   Source/Core/Visualization/Mapper/CellByCellMetropolisSampling.cpp \
   Source/Core/Visualization/Mapper/CellByCellRejectionSampling.cpp \
   Source/Core/Visualization/Mapper/CellByCellUniformSampling.cpp \
   Source/Core/Visualization/Mapper/ColorMap.cpp \
   Source/Core/Visualization/Mapper/DiamondGlyph.cpp \
   Source/Core/Visualization/Mapper/ExternalFaces.cpp \
   Source/Core/Visualization/Mapper/ExtractEdges.cpp \
   Source/Core/Visualization/Mapper/ExtractVertices.cpp \
   Source/Core/Visualization/Mapper/FrequencyTable.cpp \
   Source/Core/Visualization/Mapper/GlyphBase.cpp \
   Source/Core/Visualization/Mapper/HexahedralCell.cpp \
   Source/Core/Visualization/Mapper/HitAndMissSampling.cpp \
   Source/Core/Visualization/Mapper/Isosurface.cpp \
   Source/Core/Visualization/Mapper/MapperBase.cpp \
   Source/Core/Visualization/Mapper/MarchingCubes.cpp \
   Source/Core/Visualization/Mapper/MarchingCubesTable.cpp \
   Source/Core/Visualization/Mapper/MarchingHexahedra.cpp \
   Source/Core/Visualization/Mapper/MarchingHexahedraTable.cpp \
   Source/Core/Visualization/Mapper/MarchingPyramid.cpp \
   Source/Core/Visualization/Mapper/MarchingPyramidTable.cpp \
   Source/Core/Visualization/Mapper/MarchingTetrahedra.cpp \
   Source/Core/Visualization/Mapper/MarchingTetrahedraTable.cpp \
   Source/Core/Visualization/Mapper/MetropolisSampling.cpp \
   Source/Core/Visualization/Mapper/OpacityMap.cpp \
   Source/Core/Visualization/Mapper/OrthoSlice.cpp \
   Source/Core/Visualization/Mapper/PyramidalCell.cpp \
   Source/Core/Visualization/Mapper/QuadraticHexahedralCell.cpp \
   Source/Core/Visualization/Mapper/QuadraticTetrahedralCell.cpp \
   Source/Core/Visualization/Mapper/RGBFormulae.cpp \
   Source/Core/Visualization/Mapper/SlicePlane.cpp \
   Source/Core/Visualization/Mapper/SphereGlyph.cpp \
   Source/Core/Visualization/Mapper/Streamline.cpp \
   Source/Core/Visualization/Mapper/StreamlineBase.cpp \
   Source/Core/Visualization/Mapper/TetrahedralCell.cpp \
   Source/Core/Visualization/Mapper/TransferFunction.cpp \
   Source/Core/Visualization/Object/AxisObject.cpp \
   Source/Core/Visualization/Object/GeometryObjectBase.cpp \
   Source/Core/Visualization/Object/GlyphObject.cpp \
   Source/Core/Visualization/Object/ImageObject.cpp \
   Source/Core/Visualization/Object/LineObject.cpp \
   Source/Core/Visualization/Object/ObjectBase.cpp \
   Source/Core/Visualization/Object/PointObject.cpp \
   Source/Core/Visualization/Object/PolygonObject.cpp \
   Source/Core/Visualization/Object/StructuredVolumeObject.cpp \
   Source/Core/Visualization/Object/TableObject.cpp \
   Source/Core/Visualization/Object/UnstructuredVolumeObject.cpp \
   Source/Core/Visualization/Object/VolumeObjectBase.cpp \
   Source/Core/Visualization/Pipeline/ObjectImporter.cpp \
   Source/Core/Visualization/Pipeline/PipelineModule.cpp \
   Source/Core/Visualization/Pipeline/VisualizationPipeline.cpp \
   Source/Core/Visualization/Renderer/GlyphRenderer.cpp \
   Source/Core/Visualization/Renderer/ImageRenderer.cpp \
   Source/Core/Visualization/Renderer/LineRenderer.cpp \
   Source/Core/Visualization/Renderer/ParallelCoordinatesRenderer.cpp \
   Source/Core/Visualization/Renderer/ParticleBuffer.cpp \
   Source/Core/Visualization/Renderer/ParticleBufferAccumulator.cpp \
   Source/Core/Visualization/Renderer/ParticleBufferCompositor.cpp \
   Source/Core/Visualization/Renderer/ParticleVolumeRenderer.cpp \
   Source/Core/Visualization/Renderer/PointRenderer.cpp \
   Source/Core/Visualization/Renderer/PolygonRenderer.cpp \
   Source/Core/Visualization/Renderer/Ray.cpp \
   Source/Core/Visualization/Renderer/RayCastingRenderer.cpp \
   Source/Core/Visualization/Renderer/RendererBase.cpp \
   Source/Core/Visualization/Renderer/ScatterPlotMatrixRenderer.cpp \
   Source/Core/Visualization/Renderer/ScatterPlotRenderer.cpp \
   Source/Core/Visualization/Renderer/Shader.cpp \
   Source/Core/Visualization/Renderer/VolumeRayIntersector.cpp \
   Source/Core/Visualization/Renderer/VolumeRendererBase.cpp \
   Source/Core/Visualization/Viewer/ApplicationBase.cpp \
   Source/Core/Visualization/Viewer/Background.cpp \
   Source/Core/Visualization/Viewer/Camera.cpp \
   Source/Core/Visualization/Viewer/DisplayFormat.cpp \
   Source/Core/Visualization/Viewer/DisplayList.cpp \
   Source/Core/Visualization/Viewer/FrameBuffer.cpp \
   Source/Core/Visualization/Viewer/GlobalCore.cpp \
   Source/Core/Visualization/Viewer/IDManager.cpp \
   Source/Core/Visualization/Viewer/Light.cpp \
   Source/Core/Visualization/Viewer/Material.cpp \
   Source/Core/Visualization/Viewer/Mouse.cpp \
   Source/Core/Visualization/Viewer/ObjectManager.cpp \
   Source/Core/Visualization/Viewer/RendererManager.cpp \
   Source/Core/Visualization/Viewer/ScreenBase.cpp \
   Source/Core/Visualization/Viewer/ScreenCore.cpp \
   Source/Core/Visualization/Viewer/Texture1D.cpp \
   Source/Core/Visualization/Viewer/Texture2D.cpp \
   Source/Core/Visualization/Viewer/TextureBase.cpp \
   Source/Core/Visualization/Viewer/Trackball.cpp \
   Source/Core/Visualization/Viewer/WindowBase.cpp \
   Source/Core/Visualization/Viewer/Xform.cpp \
   Source/Core/Visualization/Viewer/XformControl.cpp \
   Source/SupportGLEW/Renderer/EnsembleAverageBuffer.cpp \
   Source/SupportGLEW/Renderer/ParticleVolumeRenderer.cpp \
   Source/SupportGLEW/Renderer/PointRenderer.cpp \
   Source/SupportGLEW/Renderer/PolygonRenderer.cpp \
   Source/SupportGLEW/Renderer/RayCastingRenderer.cpp \
   Source/SupportGLEW/Viewer/BufferObject.cpp \
   Source/SupportGLEW/Viewer/FragmentShader.cpp \
   Source/SupportGLEW/Viewer/FrameBufferObject.cpp \
   Source/SupportGLEW/Viewer/GeometryShader.cpp \
   Source/SupportGLEW/Viewer/IndexBufferObject.cpp \
   Source/SupportGLEW/Viewer/PixelBufferObject.cpp \
   Source/SupportGLEW/Viewer/ProgramObject.cpp \
   Source/SupportGLEW/Viewer/RenderBuffer.cpp \
   Source/SupportGLEW/Viewer/ShaderObject.cpp \
   Source/SupportGLEW/Viewer/ShaderSource.cpp \
   Source/SupportGLEW/Viewer/Texture3D.cpp \
   Source/SupportGLEW/Viewer/TextureRectangle.cpp \
   Source/SupportGLEW/Viewer/VertexBufferObject.cpp \
   Source/SupportGLEW/Viewer/VertexShader.cpp \
   Source/SupportGLEW/shader2header.c \

OTHER_FILES  = \
   Doxyfile \
   kvs.conf
